# Sección 1. Instalación e importación

In [1]:
#!pip install numpy
import numpy as np

**Ayuda:** https://numpy.org/doc/stable/reference/routines.html#routines

**Funciones más comunes:**

1. Array Creation: arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, linspace, logspace, mgrid, ogrid, ones, ones_like, r_, zeros, zeros_like
2. Conversions: ndarray.astype, atleast_1d, atleast_2d, atleast_3d, mat
3. Manipulations: array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, ndarray.item, newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack
4. Questions: all, any, nonzero, where
5. Ordering: argmax, argmin, argsort, max, min, ptp, searchsorted, sort
6. Operations: choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real, sum
7. Basic Statistics: cov, mean, std, var
8. Basic Linear Algebra: cross, dot, outer, linalg.svd, vdot



# Sección 2. Básicos de NumPy

In [2]:
# Crear un array (unidimensional: fila)
x=np.array([1, 1, 1])
x

array([1, 1, 1])

In [3]:
type(x)

numpy.ndarray

In [4]:
# Información de un array
print('Dimensión:', x.ndim) #dimensión
print('Tamaño:', x.size) #tamaño total del array
print('Forma:', x.shape) #forma
print('Tipo:', x.dtype) #tipo de elementos

Dimensión: 1
Tamaño: 3
Forma: (3,)
Tipo: int64


In [5]:
# Cambiar el tipo de datos (de int64 a int32)
x=np.array([1, 1, 1], dtype='int32')
x

array([1, 1, 1], dtype=int32)

In [6]:
# Crear un array (unidimensional: columna)
y=np.array([[1], [1], [1]])
print(y)
type(y)

[[1]
 [1]
 [1]]


numpy.ndarray

In [7]:
# Información de un array
print('Dimensión:', y.ndim) #dimensión
print('Tamaño:', y.size) #tamaño total del array
print('Forma:', y.shape) #forma
print('Tipo:', y.dtype) #tipo de elementos

Dimensión: 2
Tamaño: 3
Forma: (3, 1)
Tipo: int64


In [8]:
# Crear un array (bidimensional: matriz)
z=np.array([[1,2], [3,4], [5,6]])
print(z)
type(z)

[[1 2]
 [3 4]
 [5 6]]


numpy.ndarray

In [9]:
# Información de un array
print('Dimensión:', z.ndim) #dimensión
print('Tamaño:', z.size) #tamaño total del array
print('Forma:', z.shape) #forma
print('Tipo:', z.dtype) #tipo de elementos

Dimensión: 2
Tamaño: 6
Forma: (3, 2)
Tipo: int64


In [10]:
# Convertir array en lista
a = x.tolist()
print(a)
type(a)

[1, 1, 1]


list

In [11]:
# Convertir lista en array
b=np.array(a)
print(b)
type(b)


[1 1 1]


numpy.ndarray

# Sección 3. Guardando e importando los datos

In [12]:
# Guardar los datos como .npy
np.save('my_matrix', z)

In [13]:
# Importar los datos guardados como .npy
matrix_z=np.load('my_matrix.npy')
matrix_z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
# Guardar los datos como .csv 
np.savetxt('my_matrix.csv', z, fmt='%d') 


In [15]:
# Importar
matrix_z2=np.loadtxt('my_matrix.csv',dtype=int)
matrix_z2

array([[1, 2],
       [3, 4],
       [5, 6]])

# Sección 4. Creando arrays y matrices

### Crear matrices de ceros, unos, y otros valores

In [16]:
# Crear una matriz de ceros 
np.zeros((6,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [17]:
# Crear una matriz de ceros (enteros) 
np.zeros((4,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [18]:
# Crear una matriz de unos (enteros) 
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [19]:
# Crear una matriz de valores fijos 

In [20]:
np.full((5,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

### Matriz identidad y diagonal

In [21]:
# Matriz identidad
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [22]:
# Matriz identidad (enteros)
np.eye(6 ,dtype=int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [23]:
#Matriz diagonal
np.diag([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

### Simular rango de valores enteros

In [24]:
# Creando un array de NumPy en base a un intervalo de valores (enteros)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(10,15)

array([10, 11, 12, 13, 14])

In [26]:
np.arange(10,45,5)

array([10, 15, 20, 25, 30, 35, 40])

### Simular valores aleatorios flotantes

In [27]:
# Creando un array de NumPy en base a un intervalo de valores (flotantes)
np.linspace(0,1) # por defecto devuelve 50 valores. Los límites están incluidos: [0,1]


array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [28]:
np.linspace(0, 1, 10) 

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [29]:
# Creando un array de NumPy en base a un intervalo de valores (flotantes) sin incluir límite superior: [0,1)
np.linspace(0,1, 5, endpoint=False) 

array([0. , 0.2, 0.4, 0.6, 0.8])

### Simular valores aleatorios enteros

In [30]:
# Simular valores aleatorios enteros
np.random.randint(3,30) # un número

16

In [31]:
np.random.randint(3,30, size = 5) # un vector

array([20, 11,  8,  5, 10])

In [32]:
np.random.randint(3,30, size = (6,4)) # una matriz

array([[10,  3, 13, 28],
       [ 3, 13, 18,  4],
       [ 3,  4, 21,  4],
       [13,  5,  6, 13],
       [ 8, 22, 12,  3],
       [23,  3,  9, 28]])

### Simular valores aleatorios flotantes

In [33]:
# Simular valores aleatorios flotantes
np.random.random() # Por defecto en [0,1)

0.8791607824326779

In [34]:
np.random.random(10) # vector de 10 elementos en [0,1)

array([0.91590417, 0.99707658, 0.17277321, 0.31314716, 0.11737359,
       0.1874833 , 0.50080527, 0.24264356, 0.76989236, 0.07784386])

In [35]:
np.random.uniform(1,10, size=20) # vector de 20 elementos en [a,b)

array([9.28181541, 2.82256321, 7.30027239, 1.22429271, 3.01481341,
       1.73574303, 2.70883248, 6.64442048, 5.25636303, 8.60181   ,
       6.04095184, 7.11181047, 8.05292498, 9.6184069 , 1.83183345,
       7.67367756, 4.88125378, 3.69539668, 8.7670364 , 2.04651595])

### Simular valores aleatorios de una Distribución Normal 

In [36]:
# Simular valores aleatorios de una Distribución Normal con media mu y desviación típica sigma
normal_values=np.random.normal(3, 6, size=25)

In [37]:
normal_values

array([-4.0146513 , -3.34056286, -0.26146511,  6.7398341 , -5.95579062,
       10.77471173,  0.29054458, 11.2635918 , -0.93208582,  9.48929837,
        2.76319273,  5.50030387, -0.957688  ,  6.35980262,  2.59965911,
        3.29936141, -3.66574923, -3.74756315, 12.21492969,  0.94542391,
       -2.89897533,  4.80020099, 10.84163421,  1.26909321,  2.60749277])

In [38]:
# Media
normal_values.mean()

2.639381747260484

In [39]:
# Desviación típica
normal_values.std()

5.291201048761554

### Simular valores aleatorios de una Distribución Bernouilli 

In [40]:
bern = np.random.choice(['T','F'], size=100)
bern

array(['T', 'F', 'T', 'F', 'T', 'T', 'T', 'F', 'F', 'T', 'T', 'F', 'F',
       'F', 'F', 'F', 'F', 'T', 'F', 'F', 'T', 'F', 'T', 'F', 'T', 'F',
       'T', 'F', 'T', 'F', 'T', 'F', 'T', 'T', 'F', 'T', 'F', 'T', 'F',
       'F', 'T', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F',
       'T', 'F', 'F', 'F', 'F', 'F', 'F', 'T', 'T', 'T', 'F', 'T', 'F',
       'F', 'F', 'F', 'T', 'T', 'T', 'F', 'T', 'F', 'F', 'F', 'F', 'F',
       'F', 'F', 'F', 'F', 'T', 'T', 'T', 'F', 'T', 'F', 'F', 'T', 'F',
       'F', 'T', 'T', 'T', 'T', 'F', 'F', 'T', 'F'], dtype='<U1')

In [41]:
# Contar los elementos de tipo T
sum(bern=='T')

38

In [42]:
# Contar los elementos de tipo F
sum(bern=='F')

62

# Sección 5. Manipulando arrays y matrices

In [43]:
# Tenemos una matriz de 3x2
print('Matrix: \n', z)
print('Shape:',z.shape)

Matrix: 
 [[1 2]
 [3 4]
 [5 6]]
Shape: (3, 2)


### Cambiar la forma

In [44]:
# Cambiar la forma de una matriz 
np.reshape(z, (2,3) )

array([[1, 2, 3],
       [4, 5, 6]])

### Extracción de valores

In [45]:
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
z[0] # primera fila completa

array([1, 2])

In [47]:
z[:,0] # primera columna completa

array([1, 3, 5])

In [48]:
z[0,0] # primera fila y primera columna

1

In [49]:
z[1,1] # segunda fila y segunda columna

4

In [50]:
z[0:2,:] # desde la primera fila hasta la segunda fila, y todas las columnas (el "2" que es el 3 no se incluye).

array([[1, 2],
       [3, 4]])

### Modificación de valores

In [51]:
z[0,0]

1

In [52]:
z[0,0] = z[0,0] + z[0,1] # 0 -> 1 + 2 = 3
z

array([[3, 2],
       [3, 4],
       [5, 6]])

In [53]:
z[2,0] = 0 # 5 -> 0
z

array([[3, 2],
       [3, 4],
       [0, 6]])

In [54]:
# Una fila completa
z[0,:] = [100, 100]
z

array([[100, 100],
       [  3,   4],
       [  0,   6]])

In [55]:
# Una columna completa
z[:,1] = [200, 200, 200]
z

array([[100, 200],
       [  3, 200],
       [  0, 200]])

### Borrado de valores


In [56]:
z

array([[100, 200],
       [  3, 200],
       [  0, 200]])

In [57]:
# Borrar el primer elemento de la matriz pasando su posición: (0,0)
z_new=np.delete(z, (0,0)) # Lo convierte en un vector porque ya no puede ser matriz
z_new


array([200,   3, 200,   0, 200])

In [58]:
# Borrar la terecera fila de la matriz, especificando el eje (axis=0). 
np.delete(z, 2, axis=0) 



array([[100, 200],
       [  3, 200]])

In [59]:
# No guarda
z

array([[100, 200],
       [  3, 200],
       [  0, 200]])

In [60]:
# Borrar la segunda fila de la matriz, especificando el eje (axis=1). 
np.delete(z, 1, axis=1) 

array([[100],
       [  3],
       [  0]])

### Inserción de valores


In [61]:
# En array
np.append(z_new, 27) # añade al final. No guarda

array([200,   3, 200,   0, 200,  27])

In [62]:
z_new

array([200,   3, 200,   0, 200])

In [63]:
z_new=np.append(z_new, 27) # guardamos

In [64]:
z_new

array([200,   3, 200,   0, 200,  27])

In [65]:
np.insert(z_new, 4, 1000) # añade en una posición (primero la posición, luego el valor). 


array([ 200,    3,  200,    0, 1000,  200,   27])

In [66]:
# No guarda
z_new

array([200,   3, 200,   0, 200,  27])

In [67]:
# Ahora en matrices
z

array([[100, 200],
       [  3, 200],
       [  0, 200]])

In [68]:
# Añadir fila al final. Hay que especificar el eje (axis=0 fila, axis=1 columna)
np.append(z, [[0,0]], axis=0)

array([[100, 200],
       [  3, 200],
       [  0, 200],
       [  0,   0]])

In [69]:
# Añadir columna al final. Hay que especificar el eje (axis=0 fila, axis=1 columna)
np.append(z, [[0], [0], [0]], axis=1)

array([[100, 200,   0],
       [  3, 200,   0],
       [  0, 200,   0]])

In [70]:
# No se ha guardado z
z


array([[100, 200],
       [  3, 200],
       [  0, 200]])

In [71]:
# Insertar. Hay que especificar el eje (axis=0 fila, axis=1 columna)
np.insert(z, 1, [0, 0], axis=0) 

array([[100, 200],
       [  0,   0],
       [  3, 200],
       [  0, 200]])

In [72]:
# Insertar. Hay que especificar el eje (axis=0 fila, axis=1 columna)
np.insert(z, 1, [0, 0, 0], axis=1) 

array([[100,   0, 200],
       [  3,   0, 200],
       [  0,   0, 200]])

### Combinar dos o más matrices


In [73]:
mat1 = np.ones((4,5), dtype=int)
mat1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [74]:
mat2 = np.zeros((4,5), dtype=int)
mat2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [75]:
# Apilado vertical
np.vstack((mat1, mat2))

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [76]:
# Apilado horizontal
np.hstack((mat1, mat2))

array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]])

### Repetición

In [77]:
mat3=np.diag([1,2,3])
mat3

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [78]:
np.tile(mat3, 4) # repite x4 la matriz horizontalmente (por columnas)

array([[1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0],
       [0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0],
       [0, 0, 3, 0, 0, 3, 0, 0, 3, 0, 0, 3]])

In [79]:
np.tile(mat3, (2,3)) # repite x2 en filas y x3 en columnas

array([[1, 0, 0, 1, 0, 0, 1, 0, 0],
       [0, 2, 0, 0, 2, 0, 0, 2, 0],
       [0, 0, 3, 0, 0, 3, 0, 0, 3],
       [1, 0, 0, 1, 0, 0, 1, 0, 0],
       [0, 2, 0, 0, 2, 0, 0, 2, 0],
       [0, 0, 3, 0, 0, 3, 0, 0, 3]])

In [80]:
np.tile(mat1, 3) # repite x3 la matriz horizontalmente

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [81]:
mat3

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [82]:
# Repetición por valores (se especifican las repeticiones)
np.repeat(mat3, 2) # 2 reps. Devuelve array

array([1, 1, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 3, 3])

In [83]:
# Repetición por filas (se especifican las repeticiones)
np.repeat(mat3, 2, axis=0) # 2 reps de cada fila. Devuelve matriz

array([[1, 0, 0],
       [1, 0, 0],
       [0, 2, 0],
       [0, 2, 0],
       [0, 0, 3],
       [0, 0, 3]])

In [84]:
# Repetición por columnas (se especifican las repeticiones)
np.repeat(mat3, 3, axis=1) # 3 reps de cada columna. Devuelve matriz

array([[1, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 2, 2, 2, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 3, 3]])

### Diagonal

In [85]:
mat3

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [86]:
np.diag(mat3)

array([1, 2, 3])

In [87]:
np.diag(np.diag(mat3))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [88]:
#Modificar la diagonal de una matriz
mat3[np.diag_indices(mat3.shape[0])]=9
mat3

array([[9, 0, 0],
       [0, 9, 0],
       [0, 0, 9]])

In [89]:
mat3[np.diag_indices(mat3.shape[0])]=[100,200,300]
mat3

array([[100,   0,   0],
       [  0, 200,   0],
       [  0,   0, 300]])

# Sección 6. Operaciones lógicas

In [90]:
# Dónde se cumple una condición. Indexado booleano
mat3>0

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [91]:
# Para obtener los valores exactos que la cumplen
mat3[mat3>0]

array([100, 200, 300])

In [92]:
# Modificar los valores que la cumplen

In [93]:
mat3[mat3>0] = -5

In [94]:
mat3

array([[-5,  0,  0],
       [ 0, -5,  0],
       [ 0,  0, -5]])

In [95]:
# Varias condiciones. Usar paréntesis.
(mat3>0) | (mat3<-3) # condición "|"= ó

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [96]:
(mat3>0) & (mat3<-3) # condición "&"= y

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [97]:
(mat3>-1) & (mat3<1) & (mat3<5) # otra

array([[False,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [98]:
# Obtener los valores que la cumplen
mat3[(mat3>-1) & (mat3<1) & (mat3<5) ] 

array([0, 0, 0, 0, 0, 0])

In [99]:
mat3

array([[-5,  0,  0],
       [ 0, -5,  0],
       [ 0,  0, -5]])

In [100]:
# Índices donde se cumple
idx = np.where(mat3<0)
idx

(array([0, 1, 2]), array([0, 1, 2]))

In [101]:
mat3[idx]

array([-5, -5, -5])

In [102]:
# Comparar dos matrices

In [103]:
mat1=np.diag([1,2,3])
mat1

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [104]:
mat2=np.diag([4,5,6])
mat2

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [105]:
mat1==mat2

array([[False,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [106]:
# Contar en cuántos elementos coinciden
np.sum(mat1==mat2) # 6 trues

6

In [107]:
# Contar en cuántos elementos NO coinciden
np.sum(mat1!=mat2) # != significa "desigual"

3

In [108]:
# Comparar en su totalidad (útil cuando la dimensión es muy alta)
np.array_equal(mat1,mat2)

False

# Sección 7. Ordenación

In [109]:
values=[100, 98, 40, 24, 99, 50, 20, 20, 20, 1, 0, 101]
values

[100, 98, 40, 24, 99, 50, 20, 20, 20, 1, 0, 101]

In [110]:
np.sort(values) # no destructivo

array([  0,   1,  20,  20,  20,  24,  40,  50,  98,  99, 100, 101])

In [111]:
values.sort() # destructivo
values

[0, 1, 20, 20, 20, 24, 40, 50, 98, 99, 100, 101]

In [112]:
# Con axis = 0 ordena cada fila como si fuera un vector independiente. Con axis=1 ordena cada columna como si fuera un vector independiente.

# Sección 8. Matemática y aritmética

### Constantes pre-definidas

In [113]:
np.Inf # infty

inf

In [114]:
np.nan # not a number (nan)

nan

In [115]:
np.e

2.718281828459045

In [116]:
np.pi

3.141592653589793

### Operaciones con matrices

In [117]:
mat1

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [118]:
mat2

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [119]:
# Suma 
mat1+mat2

array([[5, 0, 0],
       [0, 7, 0],
       [0, 0, 9]])

In [120]:
# Resta
mat1-mat2

array([[-3,  0,  0],
       [ 0, -3,  0],
       [ 0,  0, -3]])

In [121]:
# Producto elemento a elemento
mat1*mat2

array([[ 4,  0,  0],
       [ 0, 10,  0],
       [ 0,  0, 18]])

In [122]:
# División flotante (nan por 0/0)
mat1 / mat2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([[0.25,  nan,  nan],
       [ nan, 0.4 ,  nan],
       [ nan,  nan, 0.5 ]])

In [123]:
# División entera (nan por 0/0)
mat1 // mat2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [124]:
#Operaciones entre matriz y escalar
mat1

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [125]:
mat1 + 100 # agrega el escalar a cada elemento

array([[101, 100, 100],
       [100, 102, 100],
       [100, 100, 103]])

In [126]:
mat1 - 50 

array([[-49, -50, -50],
       [-50, -48, -50],
       [-50, -50, -47]])

In [127]:
mat1 ** 2

array([[1, 0, 0],
       [0, 4, 0],
       [0, 0, 9]])

### Operaciones con matrices de diferentes dimensiones (broadcasting si se cumplen condiciones)

In [128]:
mat1 

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [129]:
mat1 + [100,200,300] # agrega la fila a cada fila

array([[101, 200, 300],
       [100, 202, 300],
       [100, 200, 303]])

In [130]:
mat1

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [131]:
mat1 + [[50],[60],[70]] # agrega la columna a cada columna

array([[51, 50, 50],
       [60, 62, 60],
       [70, 70, 73]])

### Funciones universales

In [132]:
mat1

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [133]:
# Raíz cuadrada
np.sqrt(mat1)

array([[1.        , 0.        , 0.        ],
       [0.        , 1.41421356, 0.        ],
       [0.        , 0.        , 1.73205081]])

In [134]:
# Seno
np.sin(mat1)

array([[0.84147098, 0.        , 0.        ],
       [0.        , 0.90929743, 0.        ],
       [0.        , 0.        , 0.14112001]])

In [135]:
#Logaritmo
np.log(mat1+3)

array([[1.38629436, 1.09861229, 1.09861229],
       [1.09861229, 1.60943791, 1.09861229],
       [1.09861229, 1.09861229, 1.79175947]])

In [136]:
# Aprox por arriba
np.ceil(np.log(mat1+3))

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [137]:
# Aprox por abajo
np.floor(np.log(mat1+3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [138]:
# Aprox 
np.round(np.log(mat1+3))

array([[1., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])

In [139]:
mat3

array([[-5,  0,  0],
       [ 0, -5,  0],
       [ 0,  0, -5]])

In [140]:
# Nueva matriz
mat3=mat2+2
mat3[2,:]=mat3[2,:]*2
mat3=np.append(mat3, [[15,15,15]], axis=0)
mat3

array([[ 6,  2,  2],
       [ 2,  7,  2],
       [ 4,  4, 16],
       [15, 15, 15]])

In [141]:
# Suma todos los elementos de las filas, por cada columna (resultado array de dim = num de columnas)
np.sum(mat3,axis=0)

array([27, 28, 35])

In [142]:
# Suma todos los elementos de las columnas, por cada fila (resultado array de dim = num de filas)
np.sum(mat3,axis=1)

array([10, 11, 24, 45])

# Sección 9. Estadística

In [143]:
# Contar los valores únicos
randomize = np.random.randint(1, 11, size = 25)
randomize

array([ 9, 10,  1,  5,  8,  3,  2,  3,  3,  9,  5,  1,  1,  3,  4,  2,  2,
        5,  6,  2,  4,  8,  4,  3,  5])

In [144]:
np.unique(randomize) # valores únicos sin repeticiones que aparecen en el vector

array([ 1,  2,  3,  4,  5,  6,  8,  9, 10])

In [145]:
np.unique(randomize, return_counts=True) # valores únicos sin repeticiones que aparecen en el vector, y abajo la frecuencia de cada uno

(array([ 1,  2,  3,  4,  5,  6,  8,  9, 10]),
 array([3, 4, 5, 3, 4, 1, 2, 2, 1]))

In [146]:
# Contar los valores distrintos de cero
np.count_nonzero(randomize)

25

In [147]:
# Contar los valores distrintos de cero que cumplen una condición lógica
np.count_nonzero(randomize>5)

6

In [148]:
mat3

array([[ 6,  2,  2],
       [ 2,  7,  2],
       [ 4,  4, 16],
       [15, 15, 15]])

In [149]:
# Media 
np.mean(mat3)

7.5

In [150]:
# Vector de medias de cada columna
np.mean(mat3 , axis=0)

array([6.75, 7.  , 8.75])

In [151]:
# Desviación típica
np.std(mat3)

5.693563617512908

In [152]:
# Vector de desviaciones típicas de cada columna
np.std(mat3 , axis=0)

array([4.96865173, 4.94974747, 6.75925292])

In [153]:
# Mediana
np.median(mat3)

5.0

In [154]:
# Vector de medianas de cada columna
np.median(mat3 , axis=0)

array([5. , 5.5, 8.5])

In [155]:
# Máximo
np.max(mat3) 

16

In [156]:
# Mínimo
np.min(mat3)

2

In [157]:
# Máximo de cada columna
np.max(mat3, axis = 0) 

array([15, 15, 16])

In [158]:
# Mínimo de cada columna
np.min(mat3, axis = 0) 

array([2, 2, 2])

In [159]:
mat3

array([[ 6,  2,  2],
       [ 2,  7,  2],
       [ 4,  4, 16],
       [15, 15, 15]])

In [160]:
# Índice de los valores máximos 
idx = np.argmax(mat3, axis = 0) 
idx

array([3, 3, 2])

In [161]:
# Índice de los valores mínimos (devuelve índice de la fila y si hay varios devuelve el primer lugar)
idx = np.argmin(mat3, axis = 0) 
idx

array([1, 0, 0])

In [162]:
# Evaluar los índices para obtener los elementos 
mat3[idx , range(mat3.shape[1])] # Coincide con np.min(mat3, axis = 0) 

array([2, 2, 2])

# Sección 10. Álgebra

### Producto de matrices

In [163]:
mat1


array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [164]:
mat2

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [165]:
mat3

array([[ 6,  2,  2],
       [ 2,  7,  2],
       [ 4,  4, 16],
       [15, 15, 15]])

In [166]:
# Transpuesta
mat3=np.transpose(mat3)
mat3

array([[ 6,  2,  4, 15],
       [ 2,  7,  4, 15],
       [ 2,  2, 16, 15]])

In [167]:
# Producto de dos matrices (nxp * pxm)
np.dot(mat2, mat3)

array([[24,  8, 16, 60],
       [10, 35, 20, 75],
       [12, 12, 96, 90]])

In [168]:
# Otra forma 
mat2 @ mat3

array([[24,  8, 16, 60],
       [10, 35, 20, 75],
       [12, 12, 96, 90]])

In [169]:
# Determinante
np.linalg.det(mat2)


119.99999999999997

In [170]:
# Inversa
mat1_inv=np.linalg.inv(mat1)
mat1_inv

array([[1.        , 0.        , 0.        ],
       [0.        , 0.5       , 0.        ],
       [0.        , 0.        , 0.33333333]])

In [171]:
mat1 @ mat1_inv

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [172]:
# Otra forma de obtener transpuesta
mat3.T

array([[ 6,  2,  2],
       [ 2,  7,  2],
       [ 4,  4, 16],
       [15, 15, 15]])

In [173]:
# Elevar a una potencia (tiene que ser una matriz cuadrada)
np.linalg.matrix_power(mat2,3)

array([[ 64,   0,   0],
       [  0, 125,   0],
       [  0,   0, 216]])